### ISSUE TITLE
Refresh token itself gets invalidated after refreshing access token

### ISSUE THREAD

**Issue by jithin-sukumar** [ConsumerDataRight/mock-data-holder#21]
**Describe the bug**
When the token endpoint (`/connect/token`) is invoked with `refresh_token` grant for the first time, it returns a new access token but the subsequent calls with the returned refresh_token fails (since it isn't a rotating refreshing token, same refresh_token is returned). Apparently, the code is revoking the refresh token from PersistedGrant DB but returning the same refresh_token.

**To Reproduce**
1. Generate a `request_uri` using `pushed_authorization_request_endpoint` (`/connect/par`)
2. Follow the consequent OAuth flow and grant consent to bank account(s)
3. Call the refresh token endpoint (`/connect/token`) with the refresh token received in step-2
4. Repeat step-3 with the refresh_token received in step-3
5. See error

**Expected behaviour**
Calling the token endpoint multiple times with the refresh token returned in step-3 should always generate a new access token unless the `sharing_duration` has expired.

**Screenshots**

**Additional context**
I am not completely aware of the mock-data-holder code base but I suspect that the issue is caused because the refresh token's key is being [revoked from PersistedGrant database](https://github.com/ConsumerDataRight/mock-data-holder/blob/v0.1.0/Source/CDR.DataHolder.IdentityServer/Services/TokenResponseGenerator.cs#L361-L364) when [handling the ProcessRefreshTokenRequestAsync](https://github.com/ConsumerDataRight/mock-data-holder/blob/v0.1.0/Source/CDR.DataHolder.IdentityServer/Services/TokenResponseGenerator.cs#L128). As a hot-fix, I made a [small change for my local development environment](https://github.com/jithin-sukumar/mock-data-holder/commit/25025d46c30add8d19bb70103d8ed1572b66d5f2) and it works as expected but I am not completely sure if this is the appropriate way. Any comments or suggestions from the mock-data-holder maintainers will be appreciated.

**Comment by CDR-AndrewG** [comment]
Thank you for getting in touch with us to raise this issue.

We have been unable to replicate the documented scenario following the provided steps. If possible, could you please provide a code sample that allows us to run through this scenario? 

Alternatively, we have an upcoming release that we believe will address the issue. You could wait for that release and try out the scenario again.

**Comment by CDR-AndrewG** [comment]
Hi, our release addressing this issue is now available in the develop and main branch. Please reach out again if you get a repeat of this issue.
