### ISSUE TITLE
Missing x-v header

### ISSUE THREAD

**Issue by tom-schier** [ConsumerDataRight/mock-data-holder#24]
**Describe the bug**
The mandatory header x-v is not being returned

**To Reproduce**
Steps to reproduce the behaviour:
1. Call the discovery/status or the discovery/outages endpoint 
2. Examine the header being returned

**Expected behaviour**
Return the x-v header as per DSB published standard

**Comment by CDR-AndrewG** [comment]
Thank you for getting in touch with us to raise this issue.

We have run replicated the issue using steps provided and cross checked against the standard.

We have logged the issue and will include a fix in a future release.

**Comment by CDR-AndrewG** [comment]
The fix for this issue has now been merged in to the main branch. https://github.com/ConsumerDataRight/mock-data-holder/pull/37
