### ISSUE TITLE
 Mismatch between the Docker command, Docker Compose and the hosts entry file

### ISSUE THREAD

**Issue by danieljeganathan** [ConsumerDataRight/mock-data-holder#25]
Hi Team,

Thanks for this wonderful mocks utility. It's really helping us a lot.

There are some typos or mismatch between the Docker command, Docker Compose and the hosts entry file.

Here in docker command we are setting host -h as "mock-cdr-data-holder" but in host and docker compose as "mock-data-holder". The same issues is with register and data recipient as well.

Docker Command:

docker run -d -h mock-cdr-data-holder -p 8000:8000 -p 8001:8001 -p 8002:8002 -p 8005:8005 --name mock-cdr-data-holder consumerdataright/mock-data-holder

Docker Compose:
docker run -d -h mock-data-holder -p 8000:8000 -p 8001:8001 -p 8002:8002 -p 8003:8003 -p 8004:8004 -p 8005:8005 --name mock-data-holder consumerdataright/mock-data-holder

Host Entry: 
127.0.0.1 mock-data-holder
127.0.0.1 mock-data-recipient
127.0.0.1 mock-register

Thanks,
Daniel Jeganathan

**Comment by CDR-AndrewG** [comment]
Thank you for getting in touch with us to raise this issue and for the great feedback.

We have logged the issue and will include updated documentation in a future release.

**Comment by CDR-AndrewG** [comment]
Hi, our release addressing this issue is now available in the develop and main branch. The same update will be applied to the mock register and mock data recipient within their next releases.
