### ISSUE TITLE
Energy API implementation?

### ISSUE THREAD

**Issue by bsmithb2** [ConsumerDataRight/mock-data-holder#31]
Hi, 

Do you know when the Energy API and FAPI 1.0 Advanced Final implementations will be available to utilise? 

Thanks!

**Comment by CDR-AndrewG** [comment]
Hi,

Thank you for your query. 

We are currently working on a mock data holder for energy. Release of the code to git hub will be near the end of Q1 2022. 

We are currently discussing the FAPI 1.0 implementation within the mock data holder code base. We cannot yet provide an approximated timeframe.
