### ISSUE TITLE
Improve Static Application Security Testing Results

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataRight/mock-data-holder#32]
**Describe the bug**

I notice you've got Sonarqube setup as a workflow action however none of the identified issues (which also pinged on our internal SAST analyser) appear to have been fixed. 

Consequently, I've forked the code and produced a [public version of Sonarqube analysis](https://sonarcloud.io/summary/overall?id=perlboy_mock-data-holder) which provides an overall score of **E**.

Notable concerns are:
1) [Use of MD5 for seeding AES](https://sonarcloud.io/project/security_hotspots?id=perlboy_mock-data-holder&hotspots=AX9eLLBppaHZ15FDzNSd)
2) [Disabling of TLS verification instead of using a local CA](https://sonarcloud.io/project/issues?issues=AX9eLLBBpaHZ15FDzNSU&open=AX9eLLBBpaHZ15FDzNSU&id=perlboy_mock-data-holder)
3) [Apparent Redirect URLs based on User Input ](https://sonarcloud.io/project/issues?issues=AX9eLK7kpaHZ15FDzNQT&open=AX9eLK7kpaHZ15FDzNQT&id=perlboy_mock-data-holder)

I believe all 3 of these are OWASP baselines, there's a further 307 code smells noted: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=perlboy_mock-data-holder

**To Reproduce**
1. Enable Sonarqube 
2. Work through issues
3. Fix code

**Expected behaviour**

Good code quality should be a prerequisite when promoting an example data holder within a highly secure ecosystem.

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/4291448/156913984-8c244a10-a259-488d-8162-cb9b7672aedf.png)

**Comment by CDR-AndrewG** [comment]
Thank you for taking the time to review the Mock Data Holder and provide feedback.

The current list of Sonarqube open items can be found here - https://sonarcloud.io/summary/overall?id=ConsumerDataRight_mock-data-holder

An unreviewed Sonarqube list differs from the [reviewed Sonarqube](https://sonarcloud.io/summary/overall?id=ConsumerDataRight_mock-data-holder) list as the issues requiring no action have been closed. When reviewing the Sonarqube results, the following context was applied when deciding if an issue needed to be resolved or not - The goal of the Mock Solutions is to provide a set of tools to assist participants to develop and test their own solutions. They need to be easy to use and provide a way to see what is going on inside when dealing with requests and responses.

Transparency and code quality are important. The items that need addressing have been left open and are visible to all. A large number of the remaining items will be resolved in the next release that is being prepared.
