### ISSUE TITLE
MockData response modes not advertised via OIDC discovery endpoint (and not equivalent to the default)

### ISSUE THREAD

**Issue by mark202** [ConsumerDataRight/mock-data-holder#46]
We have identified that the MockDataHolder currently only supports "form_post" and "fragment" for "response_mode" values. If we try to pass in "query" it returns an error via callback:  "Invalid response_mode for response_type".

When we view the MockDataHolder's OIDC discovery endpoint on the sandbox (https://dh-bank.idp.cdrsandbox.gov.au/.well-known/openid-configuration) the claim "response_modes_support" is not supplied. Based on RFC 8414 (https://www.rfc-editor.org/rfc/rfc8414.html) it is an optional field, but if omitted the default is ["query", "fragment"].

We suggest that to make MockDataHolder compliant, since it only supports "form_post" and "fragment", it should include the claim "response_modes_support" with the value ["form_post", "fragment"].

**Comment by CDR-AndrewG** [comment]
Thank you for bringing this issue to our attention. The detail you provided will greatly assist us. We are currently looking into the issue further.

**Comment by CDR-AndrewG** [comment]
Hi @mark202,

This issue has been resolved in our latest release of the Sandbox. An update is also on the way to publish the fix to this repository.

**Comment by CDR-AndrewG** [comment]
Hi @mark202,

This issue has now been resolved in our GitHub repository.
