### ISSUE TITLE
Software Product Not Available 

### ISSUE THREAD

**Issue by schafer14** [ConsumerDataRight/mock-data-holder#52]
**Describe the bug**

I am receiving a 400 when hitting the PAR endpoint in the mock data holder:

```
{"error":"invalid_request","error_description":"Software Product Status is invalid"}
```

The logs are mentioning the software product is not available, but I run DCR immediately before the PAR.

**To Reproduce**
1. Start the mock-register and mock-data-holder with [docker compose](https://gist.github.com/schafer14/6ce6bc89a71c9927b047b274fabf754a#file-compose-yaml) and [seed data (truncated)](https://gist.github.com/schafer14/6ce6bc89a71c9927b047b274fabf754a#file-seed-json) for my environment.
2. Do [everything required](https://gist.github.com/schafer14/6ce6bc89a71c9927b047b274fabf754a#file-01_register-md) to get a client id with the mock data holder. 
3. Hit the [par endpoint](https://gist.github.com/schafer14/6ce6bc89a71c9927b047b274fabf754a#file-02_auth-md) with my client assertions. 

**Expected behaviour**

I don't think I should see an error?!

**Additional context**

I can hit the [GET registration/{id}](https://gist.github.com/schafer14/6ce6bc89a71c9927b047b274fabf754a#file-client_id-md) endpoint, so I assume my product should be active and available. 

I can also get successful responses from the data recipients status endpoint.

**Comment by schafer14** [comment]
I am just noticing now that in the SSA the `software_roles` field is set correctly to `data-recipient-software-product`, but when I hit the DH registration/id endpoint the `software_roles` field is empty... 

Could that be an issue with registration?

**Comment by schafer14** [comment]
Looks like this is fixed by #55.
 I'm testing with the `develop` docker tag, but it looks like tag should be created soon?!

**Comment by CDR-AndrewG** [comment]
Hi @schafer14,

Thank you for logging this issue.

Can you try keeping the record with `"SoftwareProductId": "c6327f87-687a-4369-99a4-eaacd3bb8210"` in your truncated seed data? 

This Software Product represents the mock-data-recipient [repository](https://github.com/ConsumerDataRight/mock-data-recipient) and [docker container](https://hub.docker.com/r/consumerdataright/mock-data-recipient). The default settings that go into the docker container can be seen [here](https://github.com/ConsumerDataRight/mock-data-recipient/blob/main/Source/CDR.DataRecipient.Web/appsettings.json).

Let us know if that helps.

**Comment by schafer14** [comment]
Hi @CDR-AndrewG,

Yep works perfectly. Thanks.

close #52

**Comment by schafer14** [comment]
Hi @CDR-AndrewG,

Yep works perfectly. Thanks.
